# Brewfile

# core utilities
brew "btop"
brew "cloud-sql-proxy"
brew "eza"
brew "ffmpeg"
brew "git"
brew "go"
brew "mkcert"
brew "starship"
brew "uv"

# javascript/node
brew "node"
brew "nvm"
brew "pnpm"

# services
brew "redis"

# cli tools
brew "bat"       
brew "fd"
brew "fzf"       
brew "trash"
brew "zoxide"

# zsh
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# cask apps
cask "claude-code"
cask "font-meslo-lg-nerd-font"
cask "gcloud-cli"
cask "mounty"
cask "ngrok"
cask "brave-browser"
cask "bruno"
cask "cursor"
cask "figma"
cask "ghostty"
cask "notion-calendar"
cask "obsidian"
cask "raycast"
cask "spotify"
cask "surfshark"
cask "zoom"
cask "docker"

# cursor extensions
vscode "bradlc.vscode-tailwindcss"
vscode "charliermarsh.ruff"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "pdconsec.vscode-print"
vscode "ritwickdey.liveserver"
vscode "robertz.code-snapshot"
vscode "twxs.cmake"
vscode "unifiedjs.vscode-mdx"
vscode "xabikos.javascriptsnippets"
vscode "xyc.vscode-mdx-preview"
vscode "zhuangtongfa.material-theme"
